[package]
name = "p2p-app1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p = "0.44.0"
futures = "0.3.1"
async-std = {version = "1.9.0", features = ["attributes"]}